selected_profiles = ["captured"]
flatpaks = [
    "com.github.cassidyjames.dippi",
    "com.google.Chrome",
    "com.lynnmichaelmartin.TimeTracker",
    "com.mattjakeman.ExtensionManager",
    "com.rafaelmardojai.Blanket",
    "dev.geopjr.Archives",
    "dev.geopjr.Collision",
    "io.github.celluloid_player.Celluloid",
    "io.github.idevecore.Valuta",
    "io.github.kolunmi.Bazaar",
    "io.github.ronniedroid.concessio",
    "io.missioncenter.MissionCenter",
    "me.iepure.devtoolbox",
    "org.gaphor.Gaphor",
    "org.gnome.Mahjongg",
    "org.gnome.Solanum",
    "org.gnome.design.Emblem",
    "org.nickvision.tubeconverter",
]
system_services = []
user_services = []
dotfiles = []

[profiles.captured]
common = []

[profiles.captured.packages]
fedora = [
    "ModemManager",
    "NetworkManager",
    "NetworkManager-adsl",
    "NetworkManager-bluetooth",
    "NetworkManager-config-connectivity-fedora",
    "NetworkManager-openconnect-gnome",
    "NetworkManager-openvpn-gnome",
    "NetworkManager-ppp",
    "NetworkManager-ssh-gnome",
    "NetworkManager-tui",
    "NetworkManager-vpnc-gnome",
    "NetworkManager-wifi",
    "NetworkManager-wwan",
    "PackageKit-command-not-found",
    "PackageKit-gstreamer-plugin",
    "PackageKit-gtk3-module",
    "SwayNotificationCenter",
    "aajohan-comfortaa-fonts",
    "abrt-cli",
    "acl",
    "adobe-source-code-pro-fonts",
    "alsa-lib-devel",
    "alsa-sof-firmware",
    "alsa-ucm",
    "alsa-utils",
    "amd-gpu-firmware",
    "amd-ucode-firmware",
    "amiri-quran-fonts",
    "anaconda-install-env-deps",
    "anaconda-live",
    "at",
    "at-spi2-atk",
    "at-spi2-core",
    "atheros-firmware",
    "atop",
    "attr",
    "audit",
    "authselect",
    "avahi",
    "awww",
    "b43-fwcutter",
    "b43-openfwwf",
    "baobab",
    "bash",
    "bash-color-prompt",
    "bash-completion",
    "bc",
    "bind-utils",
    "blueman",
    "bluez-cups",
    "brcmfmac-firmware",
    "bridge-utils",
    "brltty",
    "btop",
    "btrfs-progs",
    "bzip2",
    "chatgpt",
    "chrony",
    "cifs-utils",
    "cirrus-audio-firmware",
    "clang",
    "clang-devel",
    "cliphist",
    "cmake",
    "cmatrix",
    "cndrvcups-capt",
    "cndrvcups-common",
    "code",
    "colord",
    "compsize",
    "coreutils",
    "cpio",
    "crontabs",
    "cryptsetup",
    "cups",
    "cups-browsed",
    "cups-devel",
    "cups-filters",
    "cups-pk-helper",
    "curl",
    "cyrus-sasl-plain",
    "dbus",
    "dconf",
    "decibels",
    "default-editor",
    "default-fonts-cjk-mono",
    "default-fonts-cjk-sans",
    "default-fonts-cjk-serif",
    "default-fonts-core-emoji",
    "default-fonts-core-math",
    "default-fonts-core-mono",
    "default-fonts-core-sans",
    "default-fonts-core-serif",
    "default-fonts-other-mono",
    "default-fonts-other-sans",
    "default-fonts-other-serif",
    "deltarpm",
    "desktop-backgrounds-gnome",
    "dgop",
    "diffstat",
    "dms",
    "dnf5",
    "dnf5-plugins",
    "dnsmasq",
    "dos2unix",
    "dosfstools",
    "doxygen",
    "dracut-config-rescue",
    "dracut-live",
    "dracut-network",
    "e2fsprogs",
    "ed",
    "efibootmgr",
    "egl-utils",
    "ethtool",
    "exfatprogs",
    "eza",
    "fastfetch",
    "fedora-bookmarks",
    "fedora-chromium-config",
    "fedora-flathub-remote",
    "fedora-workstation-backgrounds",
    "fedora-workstation-repositories",
    "figlet",
    "file",
    "filesystem",
    "firewalld",
    "fontawesome4-fonts",
    "fpaste",
    "fprintd-pam",
    "fwupd",
    "gamemode",
    "gdm",
    "gettext",
    "gh",
    "ghostscript",
    "ghostty",
    "git",
    "gitui",
    "glib-networking",
    "glibc",
    "glibc-all-langpacks",
    "glycin-thumbnailer",
    "gnome-backgrounds",
    "gnome-bluetooth",
    "gnome-browser-connector",
    "gnome-calculator",
    "gnome-calendar",
    "gnome-characters",
    "gnome-classic-session",
    "gnome-clocks",
    "gnome-color-manager",
    "gnome-connections",
    "gnome-contacts",
    "gnome-control-center",
    "gnome-epub-thumbnailer",
    "gnome-font-viewer",
    "gnome-initial-setup",
    "gnome-logs",
    "gnome-maps",
    "gnome-remote-desktop",
    "gnome-session-wayland-session",
    "gnome-settings-daemon",
    "gnome-shell",
    "gnome-shell-extension-background-logo",
    "gnome-software",
    "gnome-system-monitor",
    "gnome-text-editor",
    "gnome-tweaks",
    "gnome-user-docs",
    "gnome-user-share",
    "gnome-weather",
    "gnupg2",
    "golang-bin",
    "grub2-efi-ia32",
    "grub2-efi-ia32-cdboot",
    "grub2-efi-ia32-modules",
    "grub2-efi-x64",
    "grub2-efi-x64-cdboot",
    "grub2-efi-x64-modules",
    "grub2-pc",
    "grub2-tools",
    "grub2-tools-efi",
    "grub2-tools-extra",
    "grubby",
    "gst-thumbnailers",
    "gstreamer1-plugin-dav1d",
    "gstreamer1-plugin-libav",
    "gstreamer1-plugin-openh264",
    "gstreamer1-plugins-bad-free",
    "gstreamer1-plugins-good",
    "gstreamer1-plugins-ugly-free",
    "gtk3-devel",
    "gtk4-devel",
    "gtk4-layer-shell-devel",
    "gtksourceview5-devel",
    "gum",
    "gvfs-afc",
    "gvfs-afp",
    "gvfs-archive",
    "gvfs-fuse",
    "gvfs-goa",
    "gvfs-gphoto2",
    "gvfs-mtp",
    "gvfs-smb",
    "hfsplus-tools",
    "hostname",
    "hplip",
    "htop",
    "hunspell",
    "hyperv-daemons",
    "hypridle",
    "hyprlock",
    "hyprpaper",
    "hyprshutdown",
    "hyprsunset",
    "ibus-anthy",
    "ibus-chewing",
    "ibus-gtk3",
    "ibus-gtk4",
    "ibus-hangul",
    "ibus-libpinyin",
    "ibus-m17n",
    "inotify-tools",
    "intel-audio-firmware",
    "intel-gpu-firmware",
    "intel-lpmd",
    "intel-vsc-firmware",
    "iproute",
    "iptables-nft",
    "iptstate",
    "iputils",
    "irqbalance",
    "iscsi-initiator-utils",
    "isomd5sum",
    "iwlegacy-firmware",
    "iwlwifi-dvm-firmware",
    "iwlwifi-mvm-firmware",
    "kbd",
    "kbd-legacy",
    "kernel",
    "kernel-core",
    "kernel-devel",
    "kernel-modules",
    "kernel-modules-core",
    "kernel-modules-extra",
    "kexec-tools",
    "kmscon",
    "kvantum",
    "less",
    "libadwaita-devel",
    "libcxx",
    "libertas-firmware",
    "libgda-sqlite",
    "libglade2",
    "libglvnd-gles",
    "libreoffice-graphicfilter",
    "librsvg2",
    "libsane-hpaio",
    "libva-intel-media-driver",
    "libvirt",
    "linux-firmware",
    "livesys-scripts",
    "lm_sensors",
    "localsearch",
    "logrotate",
    "loupe",
    "lrzsz",
    "lsof",
    "lua",
    "lvm2",
    "mactel-boot",
    "mailcap",
    "make",
    "man-db",
    "man-pages",
    "mcelog",
    "mdadm",
    "mediawriter",
    "mesa-demos",
    "mesa-dri-drivers",
    "mesa-libEGL",
    "mesa-vulkan-drivers",
    "microcode_ctl",
    "mpage",
    "mt7xxx-firmware",
    "mtr",
    "nautilus",
    "ncurses",
    "neovim",
    "net-tools",
    "network-manager-applet",
    "nfs-utils",
    "ninja-build",
    "niri",
    "nmap-ncat",
    "noctalia-hyprland-meta",
    "nodejs22",
    "nss-mdns",
    "ntfs-3g",
    "ntfsprogs",
    "nvidia-gpu-firmware",
    "nvme-cli",
    "nwg-look",
    "nxpwireless-firmware",
    "open-vm-tools-desktop",
    "opensc",
    "openssh-clients",
    "openssh-server",
    "orca",
    "pam-devel",
    "pam_afs_session",
    "pandoc-cli",
    "papers",
    "papers-nautilus",
    "paps",
    "parted",
    "passwdqc",
    "patch",
    "patchutils",
    "pavucontrol",
    "pciutils",
    "pinentry-gnome3",
    "pinfo",
    "pipewire-alsa",
    "pipewire-config-raop",
    "pipewire-gstreamer",
    "pipewire-pulseaudio",
    "pipewire-utils",
    "pipx",
    "plocate",
    "plymouth",
    "plymouth-system-theme",
    "podman",
    "policycoreutils",
    "policycoreutils-python-utils",
    "polkit",
    "popt",
    "prefixdevname",
    "procps-ng",
    "psacct",
    "psmisc",
    "ptyxis",
    "python3-devel",
    "python3-pip",
    "python3-tkinter",
    "qcom-wwan-firmware",
    "qemu",
    "qemu-guest-agent",
    "qt6-qt5compat",
    "qt6-qtbase",
    "qt6-qtbase-gui",
    "qt6-qtdeclarative",
    "qt6-qtmultimedia",
    "qt6-qtvirtualkeyboard",
    "qt6-qtwayland-adwaita-decoration",
    "quickshell",
    "quota",
    "realmd",
    "realtek-firmware",
    "rofi",
    "rootfiles",
    "rpm",
    "rsync",
    "rsyslog",
    "rustup",
    "rygel",
    "samba-client",
    "sane-backends-drivers-scanners",
    "sddm",
    "selinux-policy-targeted",
    "setup",
    "shadow-utils",
    "shim-ia32",
    "shim-x64",
    "showtime",
    "smartmontools",
    "snapshot",
    "sos",
    "speech-dispatcher",
    "spice-vdagent",
    "spice-webdavd",
    "sssd-common",
    "sssd-kcm",
    "sssd-proxy",
    "subversion",
    "sudo",
    "supertuxkart",
    "sushi",
    "symlinks",
    "system-config-printer-udev",
    "systemd",
    "systemd-oomd-defaults",
    "systemd-resolved",
    "systemd-udev",
    "systemtap",
    "tar",
    "tcpdump",
    "teamd",
    "terra-release",
    "tesseract",
    "texlive-enumitem",
    "texlive-fontawesome5",
    "texlive-hyphenat",
    "texlive-ly1",
    "texlive-marvosym",
    "texlive-preprint",
    "texlive-scheme-basic",
    "texlive-sourcesanspro",
    "texlive-titlesec",
    "thermald",
    "time",
    "tinysparql",
    "tiwilink-firmware",
    "toolbox",
    "traceroute",
    "tree",
    "tumbler",
    "udiskie",
    "udisks2-btrfs",
    "unzip",
    "uresourced",
    "usb_modeswitch",
    "usbutils",
    "util-linux",
    "vim-enhanced",
    "vim-minimal",
    "virt-install",
    "virtualbox-guest-additions",
    "vte-profile",
    "warp-terminal",
    "waybar",
    "wget2-wget",
    "which",
    "whois",
    "wireplumber",
    "words",
    "wpa_supplicant",
    "xclip",
    "xdg-desktop-portal",
    "xdg-desktop-portal-gnome",
    "xdg-desktop-portal-gtk",
    "xdg-user-dirs-gtk",
    "xfsprogs",
    "yazi",
    "yelp",
    "zip",
    "zram-generator-defaults",
    "zsh",
]

[danklinux]
enabled = false
installer_url = "https://install.danklinux.com"
