-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "DP-3", mode = "2560x1440@144.006", position = "0x0", scale = 1.6015625, vrr = 0, bitdepth = 10 })
